[project]
name = "weather"
version = "0.1.0"
description = "Serveur MCP pour la météo aux USA"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.9.3",
]
