[project]
name = "weather"
version = "0.1.0"
description = "MCP Weather Server - Provides weather forecast and alerts"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.9.2",
]
